# encodigs

' '

# Label encoder

In [251]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [252]:
df = pd.read_csv(r"C:\Users\Laxmi\Desktop\Pyspiders\data_science\ML\train (encoding).csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [253]:
df.head

<bound method NDFrame.head of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [254]:
df.info

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [255]:
encoder = LabelEncoder()

In [256]:
df["Sex"] = encoder.fit_transform(df["Sex"])

In [257]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S

In [258]:
print(encoder.classes_)

['female' 'male']

In [259]:
from sklearn.model_selection import train_test_split

X = df[["Sex"]]
y = df["Survived"]

xtrain, xtest, ytrain, ytest = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [260]:
encoder = LabelEncoder()

xtrain["Sex"] = encoder.fit_transform(xtrain["Sex"])
xtrain

     Sex
331    1
733    1
382    1
704    1
813    0
..   ...
106    0
270    1
860    1
435    0
102    1

[712 rows x 1 columns]

In [261]:
xtest["Sex"] = encoder.transform(xtest["Sex"])
xtest

     Sex
709    1
439    1
840    1
720    0
39     0
..   ...
433    1
773    1
25     0
84     0
10     0

[179 rows x 1 columns]

In [262]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S

# one hot encoder

In [263]:
from sklearn.preprocessing import OneHotEncoder

In [264]:
encoder = OneHotEncoder(handle_unknown="ignore")

In [265]:
from sklearn.model_selection import train_test_split

X = df[["Embarked"]]
y = df["Survived"]

xtrain, xtest, ytrain, ytest = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [266]:
encoded_train = encoder.fit_transform(xtrain[["Embarked"]])

In [267]:
xtrain

    Embarked
331        S
733        S
382        S
704        S
813        S
..       ...
106        S
270        S
860        S
435        S
102        S

[712 rows x 1 columns]

In [268]:
encoded_test = encoder.transform(xtest[["Embarked"]])

In [269]:
xtest

    Embarked
709        C
439        S
840        S
720        S
39         C
..       ...
433        S
773        C
25         S
84         S
10         S

[179 rows x 1 columns]

In [270]:
encoder.get_feature_names_out()

array(['Embarked_C', 'Embarked_Q', 'Embarked_S', 'Embarked_nan'],
      dtype=object)

In [271]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S

In [272]:
encoded_train = pd.DataFrame(
    encoded_train.toarray(),
    columns=encoder.get_feature_names_out()
)

encoded_train.head()

   Embarked_C  Embarked_Q  Embarked_S  Embarked_nan
0         0.0         0.0         1.0           0.0
1         0.0         0.0         1.0           0.0
2         0.0         0.0         1.0           0.0
3         0.0         0.0         1.0           0.0
4         0.0         0.0         1.0           0.0

# Ordinal encoder

In [273]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [274]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S

In [275]:
df["Pclass"] = df["Pclass"].map({
    1: "First",
    2: "Second",
    3: "Third"
})

In [276]:
from sklearn.model_selection import train_test_split

X = df[["Pclass"]]
y = df["Survived"]

xtrain, xtest, ytrain, ytest = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [277]:
encoder = OrdinalEncoder(
    categories=[["Third", "Second", "First"]]
)

In [278]:
xtrain["Pclass"] = encoder.fit_transform(xtrain[["Pclass"]])

xtrain.head()

     Pclass
331     2.0
733     1.0
382     0.0
704     0.0
813     0.0

In [279]:
xtest["Pclass"] = encoder.transform(xtest[["Pclass"]])

xtest.head()

     Pclass
709     0.0
439     1.0
840     0.0
720     1.0
39      0.0

In [280]:
print(encoder.categories_)

[array(['Third', 'Second', 'First'], dtype=object)]

In [281]:
print(xtrain.head())
print(xtrain.dtypes)

     Pclass
331     2.0
733     1.0
382     0.0
704     0.0
813     0.0
Pclass    float64
dtype: object

# Target Encoder

In [282]:
pip install category_encoders

Requirement already satisfied: category_encoders in c:\Users\Laxmi\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in c:\Users\Laxmi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from category_encoders) (2.3.5)
Requirement already satisfied: pandas>=1.0.5 in c:\Users\Laxmi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from category_encoders) (2.3.3)
Requirement already satisfied: patsy>=0.5.1 in c:\Users\Laxmi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\Users\Laxmi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from category_encoders) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in c:\Users\Laxmi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in c:\Users\Laxmi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Laxmi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\Laxmi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\Laxmi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\Laxmi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\Users\Laxmi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\Users\Laxmi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in C:\Users\Laxmi\AppData\Roaming\Python\Python312\site-packages (from statsmodels>=0.9.0->category_encoders) (26.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [283]:
import pandas as pd

df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
    "Experience": ["Junior", "Senior", "Senior", "Junior", "Junior", "Senior", "Junior"],
    "Salary": [30000, 45000, 35000, 70000, 50000, 75000, 32000]
})

print(df)

  Department Experience  Salary
0         IT     Junior   30000
1         HR     Senior   45000
2         IT     Senior   35000
3    Finance     Junior   70000
4         HR     Junior   50000
5    Finance     Senior   75000
6         IT     Junior   32000

In [284]:
import pandas as pd
from category_encoders import TargetEncoder

In [285]:
import pandas as pd
from sklearn.model_selection import train_test_split
from category_encoders import TargetEncoder

In [286]:
X = df[["Department"]]
y = df["Salary"]

In [287]:
xtrain, xtest, ytrain, ytest = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [288]:
encoder = TargetEncoder()

In [289]:
updated_xtrain = encoder.fit_transform(xtrain, ytrain)

print(updated_xtrain)

     Department
5  55251.206404
2  49719.014873
4  52087.739662
3  55251.206404
6  49719.014873

In [290]:
updated_xtest = encoder.transform(xtest)

print(updated_xtest)

     Department
0  49719.014873
1  52087.739662

In [291]:
new_data = pd.DataFrame({
    "Department": ["HR"]
})

updated_new = encoder.transform(new_data)

print(updated_new)

     Department
0  52087.739662